### ISSUE TITLE
Bug: ODBC driver does not build on latest DuckDB version

### ISSUE THREAD

**Issue by guenp** [duckdb/duckdb-odbc#41]
When I compile the latest `main` I get this error:

```
Catalog Error: Scalar Function with name "current_database" is not in the catalog, but it exists in the core_functions extension

Please try installing and loading the core_functions extension by running:
INSTALL core_functions;
LOAD core_functions;
```

Should we add the `core_functions` extension to the [list of extensions to bundle](https://github.com/duckdb/duckdb-odbc/blob/main/vendor.py#L18)?

**Comment by guenp** [comment]
@szarnyasg can you help? We need this to build ahead of the DuckDB 1.2 release.

**Comment by carlopi** [comment]
Yes, `core_functions` needs to be added for sure to the list of extensions to be statically linked in, can you try to see if you can get further adding that in?
